routes/web.php
<?php

use App\Http\Controllers\ExportController;
use App\Http\Controllers\ImportController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\KFZController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('kfzWelcome');
})->name('home');

Route::get('KFZ/search', [KFZController::class, 'search'])->name('search');
Route::resource('KFZ', KFZController::class);


Route::get('/export-csv', [ExportController::class, 'exportCsv']);
Route::get('/export-json', [ExportController::class, 'exportJSON']);
Route::get('/export-xml', [ExportController::class, 'exportXML']);


Route::get('/importCSV', [ImportController::class, 'getImportCSV'])->name('importCSV');
Route::post('/import_csv', [ImportController::class, 'importCsv'])->name('import_csv');

Route::get('/importJSON', [ImportController::class, 'getImportJSON'])->name('importJSON');
Route::post('/import_json', [ImportController::class, 'importJson'])->name('import_json');

Route::get('/importXML', [ImportController::class, 'getImportXML'])->name('importXML');
Route::post('/import_xml', [ImportController::class, 'importXml'])->name('import_xml');

resources/views/importCSV.blade.php
@extends('kfzPlain')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <h3>CSV Import</h3>
                    <br>

                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('import_csv') }}" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('csv_file') ? ' has-error' : '' }}">
                                <label for="csv_file" class="col-md-4 control-label">CSV file to import</label>

                                <div class="col">
                                    <input id="csv_file" type="file" class="form-control" name="csv_file" required>

                                    @if ($errors->has('csv_file'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('csv_file') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="header" checked> File contains header row
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Parse CSV
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/importJSON.blade.php
@extends('kfzPlain')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <h3>JSON Import</h3>
                    <br>

                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('import_json') }}" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('json_file') ? ' has-error' : '' }}">
                                <label for="json_file" class="col-md-4 control-label">JSON file to import</label>

                                <div class="col">
                                    <input id="json_file" type="file" class="form-control" name="json_file" required>

                                    @if ($errors->has('json_file'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('json_file') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Parse JSON
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/importXML.blade.php
@extends('kfzPlain')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <h3>XML Import</h3>
                    <br>

                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('import_xml') }}" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('xml_file') ? ' has-error' : '' }}">
                                <label for="xml_file" class="col-md-4 control-label">XML file to import</label>

                                <div class="col">
                                    <input id="xml_file" type="file" class="form-control" name="xml_file" required>

                                    @if ($errors->has('xml_file'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('xml_file') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Parse XML
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/kfzPlain.blade.php
<!doctype html>
<html lang="de">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

        <link rel="stylesheet" href='../css/bootstrap-select.min.css'>
        <link rel="stylesheet" href='../css/bootstrap.min.css'>
        <link rel="stylesheet" href="../css/jquery.multiselect.css">
        <link rel="stylesheet" href='../css/styles.css'>

        <script src="js/jquery-3.3.1.min.js"></script>

        <title>KFZ Datenbank</title>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{{route('home')}}">Home</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="{{route('KFZ.index')}}">KFZ List</a>
                    </li>
                </ul>
            </div>
        </nav>

        <main>
            <div class="container">
                @yield('content')
            </div>
        </main>

        <!-- Bootstrap JavaScript -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>    
    </body>
</html>

resources/views/kfzWelcome.blade.php
@extends('kfzPlain')
@section('content')

<h1 class="center">Herzlich Willkommen</h1>
<br>
<p>Die Kennzeichenliste ist unter dem Menüpunkt "KFZ List" zu finden</p>
<br><br>
<p>Hier sind die verscheidenen Import und Export Möglichkeiten aufgeführt:</p>
<br><br>

<div class="container">
    <div class="row">
      <div class="col">Import</div>
      <div class="col">
        <form action="{{ route('importCSV') }}" method="get">
          <button type="submit" class="btn btn-success btn-sm">Import CSV</button>
        </form>
      </div>
      <div class="col">
        <form action="{{ route('importXML') }}" method="get">
          <button type="submit" class="btn btn-success btn-sm">Import XML</button>
        </form>
      </div>
      <div class="col">
        <form action="{{ route('importJSON') }}" method="get">
          <button type="submit" class="btn btn-success btn-sm">Import JSON</button>
        </form>
      </div>
    </div>
    <br><br>
    <div class="row">
      <div class="col">Export</div>
      <div class="col">
        <span data-href="/export-csv" id="csvExport" class="btn btn-success btn-sm" onclick="exportData(event.target);">Export CSV</span>
      </div>
      <div class="col">
        <span data-href="/export-xml" id="xmlExport" class="btn btn-success btn-sm" onclick="exportData(event.target);">Export XML</span>
      </div>
      <div class="col">
        <span data-href="/export-json" id="jsonExport" class="btn btn-success btn-sm" onclick="exportData(event.target);">Export JSON</span>
      </div>
    </div>
  </div>

<script>
    function exportData(_this) {
        let _url = $(_this).data('href');
        window.location.href = _url;
    }
</script>

@endsection